# Builds using pip and tests using pytest

name: Coverage

on: 
  push:
    branches:
      [master]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install sphinx numpy scipy pandas matplotlib shapely meshio
        pip install pytest-cov
        pip install .
    - name: Coverage
      run: |
        py.test --cov-report=xml --cov=. test/
        bash <(curl -s https://codecov.io/bash)